project_dir: "/home/brch/personal_projects/github/brendanchambers/respectful-ubu"
out_dir: "data/respectful_mirror/visual_poetry"

top_url: https://ubuweb.com/vp/index.html
pause_seconds: 128  # be respecful of bandwidth utilization
directory_inclusion_filter: "/vp/"
file_inclusion_filter: ".pdf"
max_nodes: 10000  # be respectful





